In [1]:
# DGL intro
# see https://docs.dgl.ai/guide/

In [2]:
import dgl
import torch as th

Using backend: pytorch


In [3]:
u, v = th.tensor([0, 0, 0, 1]), th.tensor([1,2,3,3])
g = dgl.graph((u, v))
print(g)

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [4]:
print(g.nodes())

tensor([0, 1, 2, 3])


In [5]:
print(g.edges())

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))


In [6]:
print(g.edges(form='all'))  # edge start, edge end, node ids

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))


In [7]:
g = dgl.graph((u, v), num_nodes=8)
print(g)

Graph(num_nodes=8, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [8]:
bg = dgl.to_bidirected(g)
bg.edges()

(tensor([0, 0, 0, 1, 1, 2, 3, 3]), tensor([1, 2, 3, 0, 3, 0, 0, 1]))

In [9]:
edges = th.tensor([2, 5, 3]), th.tensor([3, 5, 0])  # edges 2->3, 5->5, 3->0
g64 = dgl.graph(edges)  # DGL uses int64 by default
print(g64.idtype)

torch.int64


In [10]:
g32 = dgl.graph(edges, idtype=th.int32)  # create int32 graph
g32.idtype

torch.int32

In [11]:
g64_2 = g32.long()  # convert to 64
g32_2 = g64.int()   # convert to in32
print(f'64: {g64_2.idtype}, 32: {g32_2.idtype}')

64: torch.int64, 32: torch.int32


In [12]:
# node and edge features
g = dgl.graph(([0, 0, 1, 5], [1, 2, 2, 0]))  # 6 nodes, 4 edges

g.ndata['x'] = th.ones(g.num_nodes(), 3)  # node feature of length
g.edata['x'] = th.ones(g.num_edges(), dtype=th.int32)  # scalare integer edge feature
print(g)

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(), dtype=torch.int32)})


In [13]:
# edge weights
edges = th.tensor([0, 0, 0, 1]), th.tensor([1, 2, 3, 3])
weights = th.tensor([0.1, 0.6, 0.9, 0.7])
g = dgl.graph(edges)
g.edata['w'] = weights
g


Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={'w': Scheme(shape=(), dtype=torch.float32)})

In [14]:
# graphs on GPU
u, v = th.tensor([0, 1, 2]), th.tensor([2, 3, 4])
g = dgl.graph((u, v))
g.ndata['x'] = th.randn(5, 3)  # original cpu feature
g.device

device(type='cpu')

In [ ]:
cuda_g = g.to('cuda:0')
cuda_g.device