# Cross entropy

source: https://neptune.ai/blog/cross-entropy-loss-and-its-applications-in-deep-learning

In [1]:
import torch
import torch.nn as nn

## binary

X = torch.randn(10)  # random N(0,1) distributed float values
y = torch.randint(2, (10,), dtype=torch.float)   # uniformly distributed integers in from {0, 1}
print(X, '\n', y)

In [ ]:
X_continous_values = torch.sigmoid(X) # rescale [0, 1]
print(X)

In [15]:
X = torch.randn(10)  # random N(0,1) distributed float values
y = torch.randint(2, (10,), dtype=torch.float)   # uniformly distributed integers in from {0, 1}
print(X, '\n', y)

In [12]:
X_continous_values = torch.sigmoid(X) # rescale [0, 1]
print(X)

tensor([-0.1660, -0.4581, -0.6261, -0.9480,  0.8766, -1.1436, -3.0885, -1.5065,
         0.7975,  1.6920])


In [14]:
loss = nn.BCELoss()(X_continous_values, y)  # sum of the negative logarithm of predicted probabilities of each value
print(loss)

tensor(0.9352)


## categorical

no need to use sigmoid separately!

In [16]:
X = torch.randn(10, 5)
print(X)

tensor([[-0.6077,  0.3422,  1.1210,  0.1117,  0.2464],
        [ 0.0823, -1.4471, -1.1924, -1.8981,  1.5608],
        [-1.6820,  1.7624, -1.2353,  0.4847, -1.1121],
        [ 1.7515, -0.2493,  1.8441,  0.1136, -0.8871],
        [-0.1722,  1.5344,  0.5421, -0.1137,  0.7329],
        [ 0.3097,  0.3260, -0.0139,  1.5647,  1.3114],
        [ 0.1861, -0.0351, -0.3049, -0.3827,  0.2460],
        [ 0.3221, -0.3083,  0.8501,  0.4580, -0.9952],
        [-0.1591,  1.1320,  1.4432, -0.4367, -0.5070],
        [ 0.1325,  0.2672, -0.3751,  0.5407, -0.9217]])


In [18]:
y = torch.randint(5, (10,))
print(y)

tensor([2, 4, 2, 1, 4, 4, 2, 4, 2, 2])


In [20]:
loss = nn.CrossEntropyLoss()(X, y)
print(loss)

tensor(1.7816)
